import react from '@vitejs/plugin-react'
import tailwind from '@tailwindcss/vite'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

const builtAt = new Date().toISOString()
const buildStamp = `${builtAt.slice(2, 10).replaceAll('-', '')}.${builtAt.slice(11, 19).replaceAll(':', '')}Z`
const processEnvironment = (globalThis as typeof globalThis & {
  process?: { env?: Record<string, string | undefined> }
}).process?.env
const revision = processEnvironment?.VERCEL_GIT_COMMIT_SHA?.slice(0, 7)
const driverBuildId = revision ? `${buildStamp}-${revision}` : buildStamp

// The driver app is a separate bundle with a tight budget: no component library, no chart lib.
// `registerType: 'prompt'` — a money app must never silently serve a stale service worker
// mid-shift; the app shows an Arabic "new version" bar instead.
export default defineConfig({
  define: {
    __ASH_DRIVER_BUILD_ID__: JSON.stringify(driverBuildId),
  },
  plugins: [
    react(),
    tailwind(),
    VitePWA({
      registerType: 'prompt',
      workbox: {
        // The on-device OCR assets (a few MB of wasm core + traineddata) must NOT be folded into the
        // install precache — that would bloat every update. They are fetched lazily on first use and
        // then cached at runtime, so OCR still works offline after the first read.
        globIgnores: ['**/tesseract/**'],
        runtimeCaching: [
          {
            urlPattern: ({ url }: { url: URL }) => url.pathname.startsWith('/tesseract/'),
            handler: 'CacheFirst',
            options: {
              cacheName: 'tesseract-ocr',
              expiration: { maxEntries: 40 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
      manifest: {
        name: 'ASH Delivery — السائق',
        short_name: 'ASH',
        lang: 'ar',
        dir: 'rtl',
        display: 'standalone',
        /* The splash flashed near-black and the app then appeared light grey under a navy header
           that matched neither. These are the app's own colours (styles.css). */
        background_color: '#eef1f8',
        theme_color: '#1b2a5c',
        start_url: '/',
        scope: '/',
        orientation: 'portrait',
        /* WITHOUT THESE CHROME NEVER OFFERS «إضافة إلى الشاشة الرئيسية». A phone-only app used
           twice a day had to be found in a browser tab every single shift, with browser chrome
           eating the vertical space and no standalone lifecycle. Generated by
           `node scripts/make-icons.mjs`. */
        icons: [
          { src: '/icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: '/icon-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
    }),
  ],
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:3000',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
    },
  },
})
