/**
 * Glyph templates for the delivery app's Arabic-Indic digits.
 *
 * GENERATED by scripts/glyph-templates.mjs from apps/driver/test/fixtures/ocr/glyphs.json.
 * Do not edit by hand — re-harvest and regenerate when new screenshots arrive.
 *
 * `distinct` is the number of DIFFERENT renderings behind a class, and it is the honest measure of
 * how much a template is worth. The sample count flatters badly: the same date «٠٨/٠٤» is reprinted
 * on twenty-two rows, so «8» has 22 samples and about two real glyphs. `UNVALIDATED` below reads
 * this field.
 */

export interface GlyphTemplate {
  readonly label: string
  /** The 12×16 grid, four pixels per hex digit. */
  readonly hex: string
  readonly aspect: number
  readonly relH: number
  readonly relY: number
  readonly distinct: number
}

export const GLYPH_TEMPLATES: readonly GlyphTemplate[] = [
  //   7 samples,  1 distinct, amount
  { label: '+', hex: '070070070070070070070fffffffff070070070070070070', aspect: 0.9412, relH: 0.9683, relY: 0.582, distinct: 1 },
  //   1 samples,  1 distinct, amount
  { label: ',', hex: '0070070071f81f8fc0fc0e00e00e00fc0fc0ff8ff8ff8ff8', aspect: 0.5714, relH: 0.4118, relY: 0.6842, distinct: 1 },
  //  15 samples,  2 distinct, amount
  { label: '-', hex: 'ffffffffffffffffffffffffffffffffffffffffffffffff', aspect: 5.1556, relH: 0.1678, relY: 0.6054, distinct: 2 },
  //   2 samples,  2 distinct, amount
  { label: '.', hex: '1f81f81f8ffffffffffff1ff1ff1ff0380381f81f8fc0fc0', aspect: 0.5714, relH: 0.4118, relY: 0.8421, distinct: 2 },
  //  22 samples,  3 distinct, date
  { label: '/', hex: '00100700700e00e00e0380380300700701c01c0180380380', aspect: 0.4652, relH: 1, relY: 0.4391, distinct: 3 },
  //  58 samples,  8 distinct, amount+date
  { label: '0', hex: '0f00f00f00f0ffffffffffffffffffffffff0f00f00f00f0', aspect: 0.769, relH: 0.2463, relY: 0.4485, distinct: 8 },
  //  17 samples, 13 distinct, amount
  { label: '1', hex: 'f80f80fc0ff01f01fc1fc07c07c07c00f00f00f00f00c00c', aspect: 0.3036, relH: 0.9866, relY: 0.4727, distinct: 13 },
  //  19 samples, 13 distinct, amount
  { label: '2', hex: 'e01e01e03f0f3fe3fe3c01c01c01c00c00e00e00e00c00c0', aspect: 0.5212, relH: 0.9834, relY: 0.4931, distinct: 13 },
  //  12 samples, 11 distinct, amount+date
  { label: '3', hex: 'e11e19e1bfbf3fe3f03801801801801800c00c0080080080', aspect: 0.6718, relH: 0.9205, relY: 0.4609, distinct: 11 },
  //  27 samples,  3 distinct, amount+date
  { label: '4', hex: '0300303c0f00c00c00c00fc03f00c03003003003003ff3ff', aspect: 0.4783, relH: 0.8257, relY: 0.3739, distinct: 3 },
  //  15 samples, 12 distinct, amount
  { label: '5', hex: '0300300fc1fe31e20ee02c03c03c03c03c02e0effeffc1e0', aspect: 0.6247, relH: 0.8511, relY: 0.452, distinct: 12 },
  //   5 samples,  3 distinct, amount
  { label: '6', hex: 'ffcffc0fc00c00c00c00c00c00c00c00c006006006007003', aspect: 0.6462, relH: 0.9656, relY: 0.4613, distinct: 3 },
  //   7 samples,  7 distinct, amount
  { label: '7', hex: '000e01e0370370638638618c1cc0cc0c8078078070030030', aspect: 0.7425, relH: 0.9699, relY: 0.5, distinct: 7 },
  //  22 samples,  2 distinct, date
  { label: '8', hex: '0200200300f00d00d00dc1dc10e10e10e303203203e03001', aspect: 0.75, relH: 0.7059, relY: 0.3568, distinct: 2 },
  //   3 samples,  2 distinct, amount+date
  { label: '9', hex: '0e00e03f8c38c18c18fd83f801e01e01e01e006006007007', aspect: 0.5926, relH: 0.8039, relY: 0.3454, distinct: 2 },
]
