#!/usr/bin/env node
/**
 * Bundle the Vercel serverless function to plain JS, ahead of Vercel's own build.
 *
 * Why this exists: `@vercel/node` runs `tsc` over a `.ts` function using default compiler options
 * — no `allowImportingTsExtensions`, no project references — which rejects this repo's explicit
 * `.ts` import extensions and mis-resolves cross-package types, even though `pnpm typecheck` is
 * green. Handing Vercel a finished `.mjs` sidesteps that entirely: no `.ts` for it to compile.
 *
 * What it does: bundles the workspace source (`@ash/*` + relative imports) into one ESM file and
 * leaves `node_modules` dependencies external, so Vercel's file tracer still ships fastify, pg,
 * @vercel/blob and friends the normal way. Money/BR1 logic is unchanged — this only rewires how
 * the same source reaches the runtime.
 */
import { build } from 'esbuild'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

await build({
  entryPoints: [join(root, 'apps/api/api/index.ts')],
  outfile: join(root, 'api/index.mjs'),
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  logLevel: 'info',
  // Self-contained: bundle fastify, pg, @vercel/blob and the workspace source all into one file,
  // so the function needs NO node_modules resolution at runtime. An earlier attempt that left
  // node_modules external failed with ERR_MODULE_NOT_FOUND on Vercel — its tracer does not follow
  // pnpm's symlinked layout from a generated file. node: builtins stay external (Node provides
  // them); pg's optional native/edge backends are excluded — pg runs fine on the pure-JS path.
  external: ['pg-native', 'pg-cloudflare', 'cloudflare:sockets'],
  banner: {
    // A working require() for any dynamic require left inside a bundled CommonJS dependency.
    js: [
      '// AUTO-GENERATED by scripts/build-api.mjs — do not edit. Source: apps/api/api/index.ts',
      "import { createRequire as __ashCreateRequire } from 'node:module';",
      'const require = __ashCreateRequire(import.meta.url);',
    ].join('\n'),
  },
})

// Vercel expects a static output directory even for a functions-only project. Every path is sent
// to the function by the catch-all rewrite, so this stays empty — it exists only to satisfy the
// build. A note file makes its purpose obvious to anyone who finds it.
mkdirSync(join(root, 'public'), { recursive: true })
writeFileSync(
  join(root, 'public', 'index.html'),
  '<!doctype html><title>ASH API</title>ASH Delivery API — all routes are served by the serverless function.\n',
)

console.log('built api/index.mjs')
